### ISSUE TITLE
Move documentation to mkdocs

### ISSUE THREAD

**Issue by barrettMCW** [barrettMCW/omero-autotagger#7]
All documentation is in readme. Should be in mkdocs with a github pages instance.

**Comment by kyeremeMCW** [comment]
docs pushed, need to publish to github pages and finish installation page

**Comment by barrettMCW** [comment]
completed as of 6b2014c2757bbe32ea26bbfad15eadef87f227cb
hosted on [readthedocs](https://omero-autotagger.readthedocs.io/en/latest/)
probably will need some updating when new release comes out
